org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
# 첫 빌드가 안정되면 true 로 켜세요 (빌드가 빨라집니다)
org.gradle.configuration-cache=false

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
